quiz_questions = {
    "What is the capital of France?": ("Paris", 1),
    "Which planet is known as the Red Planet?": ("Mars", 1),
    "Who wrote 'Romeo and Juliet'?": ("William Shakespeare", 1),
    "What is the largest ocean on Earth?": ("Pacific Ocean", 1),
    "Who is known as the Father of Computers?": ("Charles Babbage", 1),
    "What is the hardest natural substance on Earth?": ("Diamond", 2),
    "What is the chemical symbol for water?": ("H2O", 2),
    "Which planet is closest to the sun?": ("Mercury", 2),
    "Who painted the ceiling of the Sistine Chapel?": ("Michelangelo", 2),
    "Which element has the atomic number 1?": ("Hydrogen", 2),
    "What is the tallest mountain in the world?": ("Mount Everest", 3),
    "Who discovered penicillin?": ("Alexander Fleming", 3),
    "What is the largest desert in the world?": ("Sahara", 3),
    "What is the currency of Japan?": ("Yen", 3),
    "Who was the first President of the United States?": ("George Washington", 3),
    "What is the largest bone in the human body?": ("Femur", 4),
    "Who is the author of 'Harry Potter' series?": ("J.K. Rowling", 4),
    "What is the speed of light?": ("299,792,458 meters per second", 4),
    "What is the largest planet in our solar system?": ("Jupiter", 4),
    "Who developed the theory of relativity?": ("Albert Einstein", 4),
    "What is the smallest country in the world?": ("Vatican City", 5),
    "Which country is known as the Land of the Rising Sun?": ("Japan", 5),
    "Who invented the telephone?": ("Alexander Graham Bell", 5),
    "What is the boiling point of water?": ("100°C", 5),
    "What is the main ingredient in guacamole?": ("Avocado", 5),
    "What is the capital city of Canada?": ("Ottawa", 6),
    "Who is the Greek god of the sea?": ("Poseidon", 6),
    "What is the most widely spoken language in the world?": ("Mandarin Chinese", 6),
    "Who wrote 'To Kill a Mockingbird'?": ("Harper Lee", 6),
    "What is the name of the longest river in the world?": ("Nile", 6),
    "Who was the first man to step on the moon?": ("Neil Armstrong", 7),
    "What is the chemical formula for table salt?": ("NaCl", 7),
    "Who was the first female Prime Minister of the United Kingdom?": ("Margaret Thatcher", 7),
    "What is the largest mammal in the world?": ("Blue Whale", 7),
    "Who painted the 'Mona Lisa'?": ("Leonardo da Vinci", 7),
    "What is the capital of Australia?": ("Canberra", 8),
    "What is the smallest prime number?": ("2", 8),
    "Who is known as the Iron Lady?": ("Margaret Thatcher", 8),
    "What is the national sport of Japan?": ("Sumo Wrestling", 8),
    "What is the currency of India?": ("Rupee", 8),
}